import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Mysection from "@/components/Mysection";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();
  const section4 = useRef();

  function scrollTo(section) {
    section.current.scrollIntoView({ behavior: "smooth" });
  }

  return (
    <div className={`container${styles.continer}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={section1}>
        <Mysection
          image={`/images/sunset.jpeg`}
          headline={`KW Wellness`}
          showHeadline={false}
          scrollTo={scrollTo}
          goToSectionRef={section2}
          showArrow={true}
          showText={false}
        />
      </div>
      <div ref={section2}>
        <Mysection
          image={`/images/field.jpeg`}
          headline={`It's a proven fact: Investing in wellness yields major returns. Through education, training, and events, KW Wellness offers you opportunities to invest in meaningful experiences and build powerful practices that lead to greater health and well-being, and result in a shared Return on Wellness (ROW).
          Wellness is a universal term that has a personal meaning. An umbrella community, KW Wellness supports other communities that have a shared mission and vision of supporting well-being.`}
          scrollTo={scrollTo}
          goToSectionRef={section3}
          showArrow={true}
          showHeadline={true}
          showText={false}
        />
      </div>
      <div ref={section3}>
        <Mysection
          image={`/images/trees.jpeg`}
          headline={`Upcoming Events`}
          showArrow={true}
          scrollTo={scrollTo}
          goToSectionRef={section4}
          showHeadline={true}
          showText={true}
          pdf={`/images/CIVANA.pdf`}
        />
      </div>
      <div ref={section4}>
        <Mysection
          image={`/images/rocks.jpeg`}
          headline={`Contact page`}
          scrollTo={scrollTo}
          goToSectionRef={section1}
          showArrow={true}
          showHeadline={true}
          showText={false}
        />
      </div>
    </div>
  );
}
