import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Mysection from "@/components/Mysection";
import styles from "@/styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();
  const section4 = useRef();

  function scrollTo(section) {
    section.current.scrollIntoView({ behavior: "smooth" });
  }

  return (
    <div className={`container${styles.continer}`}>
      <Head>
        <title>KW Wellness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={section1}>
        <Mysection
          image={`/images/yellowFlowers.jpeg`}
          headline={`KW Wellness`}
          showHeadline={false}
          scrollTo={scrollTo}
          goToSectionRef={section2}
          showArrow={true}
          showText={false}
          showContacts={false}
          showNav={false}
          showAbout={false}
        />
      </div>
      <div ref={section2}>
        <Mysection
          image={`/images/wellness.jpeg`}
          showAbout={true}
          headline={`About`}
          scrollTo={scrollTo}
          goToSectionRef={section3}
          showArrow={true}
          showHeadline={true}
          showText={false}
          showContacts={false}
          showNav={true}
        />
      </div>
      <div ref={section3}>
        <Mysection
          image={`/images/stretch.jpeg`}
          headline={`Events`}
          showArrow={true}
          scrollTo={scrollTo}
          goToSectionRef={section4}
          showHeadline={true}
          showText={true}
          pdf={`/images/CIVANA.pdf`}
          showContacts={false}
          showNav={true}
          showAbout={false}
        />
      </div>
      <div ref={section4}>
        <Mysection
          // image={`/images/steam.jpeg`}
          // image={`https://wallpapers.com/images/hd/serenity-7ta1a89gzc1744fk.jpg`}
          image={`/images/flowers.jpeg`}
          headline={`Contact`}
          scrollTo={scrollTo}
          goToSectionRef={section1}
          showArrow={true}
          showHeadline={true}
          showText={false}
          showContacts={true}
          showNav={true}
          showAbout={false}
        />
      </div>
    </div>
  );
}
